### ISSUE TITLE
Не правильно

### ISSUE THREAD

**Issue by sqdzy** [hedw1qqq/fung-alghs#2]
![1709847203542](https://github.com/user-attachments/assets/fbb24b23-eec0-4812-821f-aa8e0b44781e)

**Comment by hedw1qqq** [comment]
![avatars-FdR5Hjs3cfl5tYK1-RZHouA-t500x500](https://github.com/user-attachments/assets/f9d851e4-cb99-44cf-8cdf-8e7d026b318e)

**Comment by hedw1qqq** [comment]
![avatars-AvoVjq16Cpi7ovtY-FP24cQ-t500x500](https://github.com/user-attachments/assets/907c485e-6a9b-4d03-b3c4-b399566cdfb0)
